# Generated by Django 4.2.2 on 2023-06-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('bike_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bike_type', models.CharField(max_length=255)),
                ('wheels', models.IntegerField()),
                ('weight', models.FloatField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('condition', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('manager', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('telephone_number', models.CharField(max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bikemodel')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branchmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('route_type', models.CharField(max_length=255)),
                ('length', models.FloatField(max_length=255)),
                ('date', models.DateField()),
                ('weather', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Return_bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_time', models.DateTimeField()),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bikemodel')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branchmodel')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customermodel')),
            ],
        ),
        migrations.AddField(
            model_name='customermodel',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.routemodel'),
        ),
    ]
